version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        
        HTTP_PROXY: http://192.168.113.101:8080
        HTTPS_PROXY: http://192.168.113.101:8080
  
    container_name: inv-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
  
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./inv-api.db

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

